name: SridharKalalae

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the SridharKalalae/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/SridharKalalae -v ${{ github.workspace }}/_site:/srv/SridharKalalae/_site \
        SridharKalalae/builder:latest /bin/bash -c "chmod -R 777 /srv/SridharKalalae && SridharKalalae build --future"
